version: "3"
name: cassandra-ex

services:

  elixir:
    image: hexpm/elixir:1.13.4-erlang-24.3.3-alpine-3.15.3
    environment:
      - ERL_AFLAGS=-kernel shell_history enabled
    volumes:
      - $PWD:/cassandra_ex
    command: ["/bin/sh"]
    working_dir: /cassandra_ex
    stdin_open: true
    tty: true
    restart: always
    # depends_on:
    #   - cassandra-ex-node-1
    #   - cassandra-ex-node-2
    #   - cassandra-ex-node-3

  node:
    image: scylladb/scylla:5.0.5
    restart: always
    command: --seeds=cassandra-ex-node-1,cassandra-ex-node-2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - 9042
    deploy:
      replicas: 3

  # scylla-node2:
  #   container_name: scylla-node2
  #   image: scylladb/scylla:4.6.2
  #   restart: always
  #   command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
  #   ports:
  #     - 9042

  # scylla-node3:
  #   container_name: scylla-node3
  #   image: scylladb/scylla:4.6.2
  #   restart: always
  #   command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
  #   ports:
  #     - 9042
